name: Deploy to windcorp.ru

on:
  push:
    branches:
      # - main
      - development

jobs:
  build-and-deploy:
    name: Build and deploy code
    runs-on: alpine_with_docker
    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: GIT_SHA=${{ gitea.sha }},GIT_REF=${{ gitea.ref_name }}
          tags: ${{ secrets.DOCKER_REPOSITORY }}/kendb3:${{ gitea.ref_name }}
      - name: Notify host of new Docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: service kendb3@${{ gitea.ref_name }} reload
