"""Copies LICENSE to autogenerated_static so it can be linked to."""

from shutil import copyfile

from django.conf import settings

from . import autogenerators


def _copy_license():
    copyfile(
        src=settings.BASE_DIR / 'LICENSE',
        dst=settings.BASE_DIR / 'autogenerated_static' / 'LICENSE.txt',
    )


autogenerators.register(_copy_license)
