export * from './models.autogenerated';
import * as allModels from './models.autogenerated';

import { Packet } from './api_lib';
import { debug, error, getInjection } from 'common';

/**
 * Load injected packets.
 */
function loadInjectedPackets() {
    type Packets = {
        model: string,
        fields: string,
        packet: Packet,
    }[];

    debug('Dataman: beginning injection');

    const packets = getInjection<Packets>('injected-packets', false);
    for (const packet_and_meta of packets) {
        const modelClass = (
            (allModels as any)[packet_and_meta.model] as any
            ?? error('Injected model is not recognized')
        );

        const manager = modelClass.objects;
        manager.addData(packet_and_meta.packet, packet_and_meta.fields);
    }

    debug('Dataman: injection complete');
}

loadInjectedPackets();

export { allModels };
